# -*- coding: utf-8 -*-
"""K_Means_Mall_Customers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p18Xs_rmqmtWBQ0N3jIStlwpePQV5u1r
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Mall_Customers.csv',encoding='latin')
df

df.shape

df.info()

df.isnull().sum()

plt.figure(figsize=(20,10))
plt.subplot(1,3,1)
sns.barplot(x=df['Gender'],y=df['Annual Income (k$)'])
plt.subplot(1,3,2)
sns.barplot(x=df['Gender'],y=df['Spending Score (1-100)'])
plt.subplot(1,3,3)
sns.barplot(x=df['Gender'],y=df['Age'])

plt.figure(figsize=(20,10))
plt.subplot(1,3,1)
sns.boxplot(x=df['Gender'],y=df['Annual Income (k$)'])
plt.subplot(1,3,2)
sns.boxplot(x=df['Gender'],y=df['Spending Score (1-100)'])
plt.subplot(1,3,3)
sns.boxplot(x=df['Gender'],y=df['Age'])

df['Gender'] = df['Gender'].astype('category')
df.info()

df['Gender'] = df['Gender'].cat.codes
df

df_new = df.drop(columns=['CustomerID'])
df_new

df_new = df_new.rename(columns={'Annual Income (k$)':'Annual_Income','Spending Score (1-100)':'Spending_Score'})
df_new

scaler = StandardScaler()
df_new_scaled = pd.DataFrame(scaler.fit_transform(df_new),columns=['Gender','Age','Annual_Income','Spending_Score'])
df_new_scaled

sse =[]
for i in range(1,10):
  kmeans = KMeans(n_clusters = i,random_state=1).fit(df_new_scaled)
  sse.append(kmeans.inertia_)
sns.lineplot(x=list(range(1,10)),y=sse,color='red')

sil = []
for i in range(2,10):
  kmeans = KMeans(n_clusters=i,random_state=1).fit(df_new_scaled)
  labels = kmeans.predict(df_new_scaled)
  sil.append(silhouette_score(df_new_scaled,labels))
sns.lineplot(x=list(range(2,10)),y=sil)

kmeans = KMeans(n_clusters = 4,random_state=1).fit(df_new_scaled)
labels = kmeans.predict(df_new_scaled)
df_new['KMeans_Labels'] = labels
df_new

df['KMeans_Labels'] = labels
df

mean = df.groupby('KMeans_Labels').mean()
median = df.groupby('KMeans_Labels').median()
df_new_compare = pd.concat([mean,median],axis=0)
df_new_compare.index = ['g0 mean', 'g0 median', 'g1 mean', 'g1 median','g2 mean','g2 median','g3 mean','g3 median']
df_new_compare.T

cols = ['Age','Annual Income (k$)','Spending Score (1-100)','KMeans_Labels']
for col in cols:
  plt.figure(figsize=(10,5))
  sns.barplot(x=df['Gender'],y=col,data=df)
  plt.show()

cols = ['Gender','Age','Spending Score (1-100)']
for col in cols:
  plt.figure(figsize=(10,5))
  sns.scatterplot(x='Annual Income (k$)',y=col,hue='KMeans_Labels',data=df,palette='Dark2')
  plt.show()

cols = ['Age','Spending Score (1-100)','Annual Income (k$)']
for col in cols:
  plt.figure(figsize=(10,5))
  sns.violinplot(x='Gender',y=col,data=df,palette='Dark2')
  plt.show()

