# -*- coding: utf-8 -*-
"""Web_Scraping_IMDB_Top_Movies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QOFURAJ7wtquSgtYUUZPPrdgCjq1S9W0
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

df = pd.DataFrame()

try:
  source = requests.get('https://www.imdb.com/chart/top/')
  source.raise_for_status()
  soup = BeautifulSoup(source.text,'html.parser')
  movies = soup.find('tbody',class_='lister-list').find_all('tr')
  for movie in movies:
    name = movie.find('td',class_='titleColumn').a.text
    rank =  movie.find('td',class_='titleColumn').get_text(strip=True).split('.')[0]
    year = movie.find('td', class_='titleColumn').span.text.strip('()')
    rating = movie.find('td',class_='ratingColumn imdbRating').strong.text
    imdb = {'Name': name,'Rank': rank,'Year' : year,'Rating': rating}
    df = df.append(imdb,ignore_index=True)
except Exception as e:
  print(e)

from google.colab import drive
drive.mount('/content/drive')

df

df.to_csv('/content/drive/My Drive/Colab Notebooks/imdb.csv', index=False)